site_name: 'EI Metrics'
site_description: ' A knowledge management system for the metrics service line'
site_author: 'Erik Anderson'
copyright: 'Copyright &copy; 2019 Environmental Incentives'

#Configuration
theme: 
  name: material
  favicon: 'img/ei-logo-black.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/ei-logo-white.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

# Navigation
nav:
- Home: 'index.md'
- Project Portfolio: 
  - Portfolio: 'portfolio/project-portfolio.md'
  - Case Studies:
    - 'portfolio/ggs-hqt/ggs-hqt.md'
    - 'portfolio/utilization-report/utilization-report.md'
- Metrics Services: 'metrics-services/how-we-work.md'
- Metrics Design Philosophy:
  - 'Overview': 'metrics-design/overview.md'
  - 'Step 1: Start at the End': 'metrics-design/step1-start-at-the-end.md'
  - 'Step 2: Map It': 'metrics-design/step2-map-it.md'
  - 'Step 3: Develop Empathy': 'metrics-design/step3-develop-empathy.md'
  - 'Step 4: Define the Problem': 'metrics-design/step4-define-the-problem.md'
  - 'Step 5: Identify a Solution': 'metrics-design/step5-identify-a-solution.md'
  - 'Step 6: Implement': 'metrics-design/step6-implement.md'
  - 'Step 7: Iterate & Adapt': 'metrics-design/step7-adapt.md'
- Project Organization:
  - 'Project Planning': 'project-organization/project-planning.md'
- Git:
  - 'Install Git': 'git/install-configure-git.md'
  - 'Create Project': 'git/initializing-git.md'
  - 'Common Workflow': 'git/common-workflow.md'
  - 'Collaborating with Git': 'git/collaborating-with-git.md'
  - 'Additional Reference': 'git/additional-reference.md'
- Development:
  - 'Command Line Tools': 'development/command-line-tools.md'
  - 'Scheduling Tasks': 'development/scheduling-tasks.md'
  - 'Environment Variables': 'development/environment-variables.md'
  - 'Virtual Environments': 'development/virtual-environments.md'
- Deployment:
  - 'Deployment Overview': 'deployment/deployment-overview.md'
  - 'Heroku': 'deployment/heroku.md'
  - 'Google API': 'deployment/google-api.md'
- Data Management:
  - 'Database Overview': 'data-management/database-overview.md'
- Data Science:
  - 'Machine Learning Tutorial': 'data-science/machine-learning-tutorial/machine-learning-tutorial.md'
- Data Visualization:
  - 'Data Visualization': 'data-visualization/data-visualization.md'
- Python Packages:
  - 'Dash': 'python-packages/dash.md'
- Additional Resources:
  - 'Scoping Canvas': 'additional-resources/scoping.md'
  - 'Product Definition': 'additional-resources/product-definition.md'
  - 'Persona Development Guide': 'additional-resources/persona-guide.md'
  - 'Interview Guide': 'additional-resources/interview-guide.md'
- How to Maintain This Site: 
  - 'Development Guide': 'development-guidance.md'
  - 'Tips & Tricks': 'notes.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true

# Social
extra:
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/eriktanderson'
    - type: 'github'
      link: 'https://github.com/eanderson-ei'
  
# Analytics
google_analytics:
  - UA-151885346-1
  - 'auto'

# Extra JavaScript
extra_javascript:
  - js/scripts.js
